version: 2.0
jobs:
 build:
   docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
      #- image: circleci/redis:latest
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore src/Gold.Redis/
     - run:
         name: Build App
         command:
           dotnet build src/Gold.Redis/
     - run:
         name: Run App
         command:
           dotnet run src/Gold.Redis/
